[build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt && pip install . && pip install -U babeldoc<0.3.0 pymupdf<1.25.3 pdfminer-six==20250416"

[deploy]
startCommand = "pdf2zh --celery worker --loglevel=info"
healthcheckPath = ""
healthcheckTimeout = 100

